return {
    "folke/snacks.nvim",
    enabled = true,
    lazy = false,
    priority = 1000,
    opts = {
        -- ─── Picker ──────────────────────────────────────────────────────────
        picker = {
            prompt = " ",
            sources = {},
            layout = {
                cycle = true,
                preset = function()
                    return vim.o.columns >= 120 and "default" or "vertical"
                end,
            },
            matcher = {
                fuzzy = true, smartcase = true, ignorecase = true,
                sort_empty = false, filename_bonus = true, file_pos = true,
            },
            sort = { fields = { "score:desc", "#text", "idx" } },
            ui_select = true,
            formatters = {
                file     = { filename_first = false },
                selected = { show_always = false, unselected = true },
            },
            previewers = {
                git  = { native = false },
                file = { max_size = 1024 * 1024, max_line_length = 500, ft = nil },
                man_pager = nil,
            },
            jump = { jumplist = true, tagstack = false, reuse_win = false },
            win = {
                input = {
                    keys = {
                        ["<Esc>"]  = "close",
                        ["<C-c>"]  = { "close", mode = "i" },
                        ["<CR>"]   = { "confirm", mode = { "n", "i" } },
                        ["G"]  = "list_bottom", ["gg"] = "list_top",
                        ["j"]  = "list_down",   ["k"]  = "list_up",
                        ["/"]  = "toggle_focus", ["q"] = "close", ["?"] = "toggle_help",
                        ["<a-d>"] = { "inspect",         mode = { "n", "i" } },
                        ["<c-a>"] = { "select_all",      mode = { "n", "i" } },
                        ["<a-m>"] = { "toggle_maximize", mode = { "i", "n" } },
                        ["<a-p>"] = { "toggle_preview",  mode = { "i", "n" } },
                        ["<a-w>"] = { "cycle_win",       mode = { "i", "n" } },
                        ["<C-w>"] = { "<c-s-w>", mode = { "i" }, expr = true, desc = "delete word" },
                        ["<C-Up>"]   = { "history_back",    mode = { "i", "n" } },
                        ["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
                        ["<Tab>"]    = { "select_and_next", mode = { "i", "n" } },
                        ["<S-Tab>"]  = { "select_and_prev", mode = { "i", "n" } },
                        ["<Down>"]   = { "list_down",       mode = { "i", "n" } },
                        ["<Up>"]     = { "list_up",         mode = { "i", "n" } },
                        ["<c-j>"]    = { "list_down",       mode = { "i", "n" } },
                        ["<c-k>"]    = { "list_up",         mode = { "i", "n" } },
                        ["<c-n>"]    = { "list_down",       mode = { "i", "n" } },
                        ["<c-p>"]    = { "list_up",         mode = { "i", "n" } },
                        ["<c-b>"]    = { "preview_scroll_up",   mode = { "i", "n" } },
                        ["<c-d>"]    = { "list_scroll_down",    mode = { "i", "n" } },
                        ["<c-f>"]    = { "preview_scroll_down", mode = { "i", "n" } },
                        ["<c-g>"]    = { "toggle_live",         mode = { "i", "n" } },
                        ["<c-u>"]    = { "list_scroll_up",      mode = { "i", "n" } },
                        ["<ScrollWheelDown>"] = { "list_scroll_wheel_down", mode = { "i", "n" } },
                        ["<ScrollWheelUp>"]   = { "list_scroll_wheel_up",   mode = { "i", "n" } },
                        ["<leader>v"] = { "edit_vsplit", mode = { "n" } },
                        ["<c-s>"]     = { "edit_split",  mode = { "i", "n" } },
                        ["<c-q>"]     = { "qflist",      mode = { "i", "n" } },
                        ["<a-i>"]     = { "toggle_ignored", mode = { "i", "n" } },
                        ["<a-h>"]     = { "toggle_hidden",  mode = { "i", "n" } },
                        ["<a-f>"]     = { "toggle_follow",  mode = { "i", "n" } },
                    },
                    b = { minipairs_disable = true },
                },
                list = {
                    keys = {
                        ["<CR>"] = "confirm", ["gg"] = "list_top", ["G"] = "list_bottom",
                        ["i"] = "focus_input", ["j"] = "list_down", ["k"] = "list_up",
                        ["q"] = "close",
                        ["<Tab>"]   = "select_and_next", ["<S-Tab>"] = "select_and_prev",
                        ["<Down>"]  = "list_down",       ["<Up>"]    = "list_up",
                        ["<a-d>"]   = "inspect",
                        ["<c-d>"]   = "list_scroll_down", ["<c-u>"] = "list_scroll_up",
                        ["zt"] = "list_scroll_top", ["zb"] = "list_scroll_bottom", ["zz"] = "list_scroll_center",
                        ["/"] = "toggle_focus",
                        ["<ScrollWheelDown>"] = "list_scroll_wheel_down",
                        ["<ScrollWheelUp>"]   = "list_scroll_wheel_up",
                        ["<c-a>"] = "select_all",
                        ["<c-f>"] = "preview_scroll_down", ["<c-b>"] = "preview_scroll_up",
                        ["<c-v>"] = "edit_vsplit", ["<leader>v"] = "edit_vsplit", ["<c-s>"] = "edit_split",
                        ["<c-j>"] = "list_down", ["<c-k>"] = "list_up",
                        ["<c-n>"] = "list_down", ["<c-p>"] = "list_up",
                        ["<a-w>"] = "cycle_win", ["<Esc>"] = "close",
                    },
                    wo = { conceallevel = 2, concealcursor = "nvc" },
                },
                preview = {
                    keys = {
                        ["<Esc>"] = "close", ["q"] = "close", ["i"] = "focus_input",
                        ["<ScrollWheelDown>"] = "list_scroll_wheel_down",
                        ["<ScrollWheelUp>"]   = "list_scroll_wheel_up",
                        ["<a-w>"] = "cycle_win",
                    },
                },
            },
            icons = {
                files       = { enabled = true },
                indent      = { vertical = "│ ", middle = "├╴", last = "└╴" },
                undo        = { saved = " " },
                ui          = { live = "󰐰 ", hidden = "h", ignored = "i", follow = "f", selected = "● ", unselected = "○ " },
                git         = { commit = "󰜘 " },
                diagnostics = { Error = " ", Warn = " ", Hint = " ", Info = " " },
                kinds = {
                    Array = " ", Boolean = "󰨙 ", Class = " ", Color = " ", Constant = "󰏿 ",
                    Constructor = " ", Copilot = " ", Enum = " ", EnumMember = " ",
                    Event = " ", Field = " ", File = " ", Folder = " ", Function = "󰊕 ",
                    Interface = " ", Key = " ", Keyword = " ", Method = "󰊕 ", Module = " ",
                    Namespace = "󰦮 ", Null = " ", Number = "󰎠 ", Object = " ", Operator = " ",
                    Package = " ", Property = " ", Reference = " ", Snippet = "󱄽 ",
                    String = " ", Struct = "󰆼 ", Text = " ", TypeParameter = " ", Unit = " ",
                    Unknown = " ", Value = " ", Variable = "󰀫 ",
                },
            },
            debug = { scores = false, leaks = false },
        },

        -- ─── Notifier ────────────────────────────────────────────────────────
        notifier = {
            enabled = true,
            timeout = 3000,
            width   = { min = 30, max = 0.4 },
            height  = { min = 1,  max = 0.6 },
            margin  = { top = 0, right = 1, bottom = 0 },
            padding = true,
            sort    = { "level", "added" },
            level   = vim.log.levels.TRACE,
            icons   = { error = " ", warn = " ", info = " ", debug = " ", trace = " " },
            keep    = function(notif) return vim.fn.getcmdpos() > 0 end,
            style       = "compact",
            top_down    = true,
            date_format = "%R",
            more_format = " ↓ %d lines ",
            refresh     = 50,
        },

        -- ─── Input ───────────────────────────────────────────────────────────
        input = {
            enabled  = true,
            icon     = " ",
            icon_hl  = "SnacksInputIcon",
            icon_pos = "left",
            prompt_pos = "title",
            win      = { style = "input" },
            expand   = true,
        },
        styles = {
            input = {
                backdrop   = false,
                position   = "float",
                border     = "rounded",
                title_pos  = "center",
                height     = 1, width = 60,
                relative   = "editor",
                noautocmd  = true,
                row        = 2,
                wo = {
                    winhighlight = "NormalFloat:SnacksInputNormal,FloatBorder:SnacksInputBorder,FloatTitle:SnacksInputTitle",
                    cursorline   = false,
                },
                bo = { filetype = "snacks_input", buftype = "prompt" },
                b  = { completion = false },
                keys = {
                    n_esc  = { "<esc>", { "cmp_close", "cancel" },    mode = "n", expr = true },
                    i_esc  = { "<esc>", { "cmp_close", "stopinsert" }, mode = "i", expr = true },
                    i_cr   = { "<cr>",  { "cmp_accept", "confirm" },  mode = "i", expr = true },
                    i_tab  = { "<tab>", { "cmp_select_next", "cmp" }, mode = "i", expr = true },
                    i_ctrl_w = { "<c-w>", "<c-s-w>", mode = "i", expr = true },
                    i_up     = { "<up>",   { "hist_up" },   mode = { "i", "n" } },
                    i_down   = { "<down>", { "hist_down" }, mode = { "i", "n" } },
                    q = "cancel",
                },
            },
        },
    },
    keys = {
        -- Buffers & files
        { mode = 'n', "<leader>,",       function() Snacks.picker.buffers()    end, desc = "Find Buffers" },
        { mode = 'n', "<leader>/",       function() Snacks.picker.grep()       end, desc = "Grep" },
        { mode = 'n', "<leader>:",       function() Snacks.picker.command_history() end, desc = "Command History" },
        { mode = 'n', "<leader><space>", function() Snacks.picker.files()      end, desc = "Find Files" },
        { mode = 'n', "<leader>fc",      function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find Config File" },
        { mode = 'n', "<leader>fb",      function() Snacks.picker.buffers()    end, desc = "Find Buffers" },
        { mode = 'n', "<leader>fg",      function() Snacks.picker.git_files()  end, desc = "Find Git Files" },
        { mode = 'n', "<leader>fr",      function() Snacks.picker.recent()     end, desc = "Find Recent" },
        -- Git
        { mode = 'n', "<leader>gl",      function() Snacks.picker.git_log()    end, desc = "Git Log" },
        { mode = 'n', "<leader>gS",      function() Snacks.picker.git_status() end, desc = "Git Status" },
        -- Grep
        { mode = 'n', "<leader>sb",      function() Snacks.picker.lines()      end, desc = "Search Buffer Lines" },
        { mode = 'n', "<leader>sB",      function() Snacks.picker.grep_buffers() end, desc = "Grep Open Buffers" },
        { mode = 'n', "<leader>sg",      function() Snacks.picker.grep()       end, desc = "Grep" },
        { mode = 'n', "<leader>sw",      function() Snacks.picker.grep_word()  end, desc = "Search Word" },
        { mode = 'x', "<leader>sw",      function() Snacks.picker.grep_word()  end, desc = "Search Selection" },
        -- Search
        { mode = 'n', '<leader>s"',      function() Snacks.picker.registers()  end, desc = "Search Registers" },
        { mode = 'n', "<leader>sa",      function() Snacks.picker.autocmds()   end, desc = "Search Autocmds" },
        { mode = 'n', "<leader>sC",      function() Snacks.picker.commands()   end, desc = "Search Commands" },
        { mode = 'n', "<leader>sd",      function() Snacks.picker.diagnostics() end, desc = "Search Diagnostics" },
        { mode = 'n', "<leader>sh",      function() Snacks.picker.help()       end, desc = "Search Help" },
        { mode = 'n', "<leader>sH",      function() Snacks.picker.highlights() end, desc = "Search Highlights" },
        { mode = 'n', "<leader>sj",      function() Snacks.picker.jumps()      end, desc = "Search Jumps" },
        { mode = 'n', "<leader>sk",      function() Snacks.picker.keymaps()    end, desc = "Search Keymaps" },
        { mode = 'n', "<leader>sl",      function() Snacks.picker.loclist()    end, desc = "Search Location List" },
        { mode = 'n', "<leader>sM",      function() Snacks.picker.man()        end, desc = "Search Man Pages" },
        { mode = 'n', "<leader>sm",      function() Snacks.picker.marks()      end, desc = "Search Marks" },
        { mode = 'n', "<leader>sn",      function() Snacks.picker.notifications({ confirm = { "yank", "close" } }) end, desc = "Search Notifications" },
        { mode = 'n', "<leader>sR",      function() Snacks.picker.resume()     end, desc = "Search Resume" },
        { mode = {'n','v'}, "<leader>sp", function() Snacks.picker.spelling()  end, desc = "Search Spelling" },
        { mode = 'n', "<leader>sq",      function() Snacks.picker.qflist()     end, desc = "Search Quickfix" },
        { mode = 'n', "<leader>su",      function() Snacks.picker.undo()       end, desc = "Search Undo History" },
        { mode = 'n', "<leader>uC",      function() Snacks.picker.colorschemes() end, desc = "Search Colorschemes" },
        { mode = 'n', "<leader>qp",      function() Snacks.picker.projects()   end, desc = "Search Projects" },
    },
}
